### ISSUE TITLE
PyTorch Implementation in the works?

### ISSUE THREAD

**Issue by ankile** [philippe-eecs/JaxDDPM#1]
Hey! This is very exciting work—will there be a PyTorch port of the algorithm, or does one already exist?

Thanks! Best, Lars

**Comment by philippe-eecs** [comment]
Not planning on making a pytorch version of this implementation of DDPM on continuous spaces, unfortunately. I've fully committed to Jax since early 2022 and have totally forgotten how to use PyTorch :).

I highly recommend picking up Jax/Flax. It's a super cool way to do deep learning
